pipeline {
   agent any 
    environment {     
    DOCKERHUB_CREDENTIALS= credentials('DOCKERHUB')     
  } 
   stages{
    
       stage('Cleaning Workspace') {
            steps {
                cleanWs()
            }
        }
      stage('Checkout from Git') {
            steps {
                git branch: 'main', credentialsId: 'github', url: 'https://github.com/sibanando/hackathon_repo.git'
            }
        }
    stage('SAST - Sonar') {
           environment {
               scannerHome = tool 'sonar-scanner';
           }
           steps {
             withSonarQubeEnv(credentialsId: 'sonar-token', installationName: 'sonar-server') {
               sh "${scannerHome}/bin/sonar-scanner -Dsonar.projectName=hackathon-proj -Dsonar.projectKey=hackathon-proj "
             }
           }
       }
     stage('Quality Check') {
            steps {
                script {
                    waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token' 
                }
            }
        }
	// stage('OWASP Dependency-Check Scan') {
     //       steps {
     //          
     //               dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'DP-Check'
     //               dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
      //         
      //      }
       // }
    
    // Building Docker images
   
     // Uploading Docker images into Docker Hub
      stage('Building image') {
        steps{    
           script {
             sh 'docker system prune -f'
             sh 'docker container prune -f'
             sh 'docker build -t  sibhanayak/pythonapp:$BUILD_NUMBER .'
            }
        }
      }
    
   stage('Login to Docker Hub') {         
      steps{                            
    	sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'                 
    	echo 'Login Completed'
      }
   }
    
    
    
    
    // Running Docker container, make sure port 8096 is opened in 
     stage('Docker Push') {
       steps{
         script {
           sh 'docker push sibhanayak/pythonapp:$BUILD_NUMBER'
         }
      }
    }
     
}
post{
    always {  
      sh 'docker logout'           
    }      
  }  
}
  
  


